---
- name: Ping
  hosts: Joomla

  tasks:
  - name: Ping Host
    ansible.builtin.ping:
      when: ping == "Pong"   
      notify: Message

  handlers:
  - name: Message
    ansible.builtin.debug:
      msg: "Host is alive"


...
