---
- name: Ping-Host
  hosts: Ubuntu

  tasks:
    - name: Ping hosts
        ping:
      when: ping == "Pong"
        msg: Message


  handlers:
    - name: Message
      debug:
        msg: "Host is alive!"
...
