---
# Hosts: where our play will run and options it will run with
hosts: linux

 # Tasks: the list of tasks that will be executed within the play, this section
 # can also be used for pre and post tasks

 tasks:
   - name: Ping hosts
     ping:
         

#handlers:

     
...
